### ISSUE TITLE
node exporter crashes from time to time

### ISSUE THREAD

**Issue by shamoya** [stereum-dev/ethereum2-docker-compose#103]
Hi all,

I'm having the node-exporter docker crash every couple of days.
The log doesn't show anything.
Does anyone have the same issue?
I'm running with prysm only.
Some output

docker-compose ps
                Name                               Command                State                    Ports
------------------------------------------------------------------------------------------------------------------------
ethereum2-docker-compose_beacon_1       /app/beacon-chain/beacon-c ...   Up         0.0.0.0:12000->12000/udp,
                                                                                    0.0.0.0:13000->13000/tcp,
                                                                                    127.0.0.1:3500->3500/tcp,
                                                                                    127.0.0.1:4000->4000/tcp,
                                                                                    127.0.0.1:8080->8080/tcp
ethereum2-docker-compose_geth_1         geth --http --http.port=85 ...   Up         0.0.0.0:30303->30303/tcp,
                                                                                    0.0.0.0:30303->30303/udp,
                                                                                    127.0.0.1:8545->8545/tcp, 8546/tcp
ethereum2-docker-compose_grafana_1      /run.sh                          Up         127.0.0.1:3000->3000/tcp
ethereum2-docker-compose_node-          /bin/node_exporter               Exit 255   9100/tcp
exporter_1
ethereum2-docker-compose_prometheus_1   /bin/prometheus --storage. ...   Up         127.0.0.1:9090->9090/tcp
ethereum2-docker-compose_renderer_1     dumb-init -- node build/ap ...   Up         8081/tcp
ethereum2-docker-compose_slasher_1      /app/slasher/slasher --con ...   Up
ethereum2-docker-compose_validator_1    /app/validator/validator - ...   Up         127.0.0.1:7500->7500/tcp,
                                                                                    127.0.0.1:8081->8081/tcp

**Comment by stefa2k** [comment]
Prometheus node export isn't the most stable thing. Got the same without running it in docker on some server.

There's a new version out of this service: https://github.com/prometheus/node_exporter/releases/tag/v1.1.0

Gonna update soon, let's hope it helps. In the meantime you can try updating yourself by editing `.env` file and change
```
PROMETHEUS_NODE_EXPORTER_DOCKER_TAG=v1.0.1
```
to
```
PROMETHEUS_NODE_EXPORTER_DOCKER_TAG=v1.1.0
```

**Comment by shamoya** [comment]
Thanks @stefa2k !
Should I close this or keep it open?

**Comment by stefa2k** [comment]
Hey @shamoya thanks for the response! Please leave it open, I'll close it when I update the version.
