### ISSUE TITLE
Grafana won't start without `user: "1000"` in docker-compose

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum2-docker-compose#17]

**Comment by CVJoint** [comment]
You can try using `user: "472:472"`.

https://grafana.com/docs/grafana/latest/installation/docker/#migrate-from-previous-docker-containers-versions

**Comment by stefa2k** [comment]
@CVJoint Thanks for your tip, unfortunately this requires a user with the ID 472 on the OS

**Comment by stefa2k** [comment]
Possible solution: use https://hub.docker.com/r/stereum/init to set correct owner & permissions of grafana's data dir.
