### ISSUE TITLE
Hardware Requirements

### ISSUE THREAD

**Issue by stefnats** [stereum-dev/ethereum2-docker-compose#198]
First, let me say thanks for the amazing project.

Can you tell me the hardware requirements for this?
I was thinking about a micro / small instance on AWS or a general purpose droplet on digitalocean.
Do you have experience with cloud providers?

**Comment by stefa2k** [comment]
Hi, the hardware requirements depend on the setup you want to run. For single client setups we run them on 2vcpus and 4gb ram when using an external eth1 node (e. g. infura.io). Also the clients differ in storage requirements, roughly 30gb should be enough right now on mainnet for one beacon chain client without geth.

In the case to run geth locally you'd need additinal cpu (4 in sum) and memory (8gb in sum) and storage (at least 1tb in sum).

Also take a look at our installer https://stereum.net/installer/ which will be web-based soon.

**Comment by stefnats** [comment]
Hey @stefa2k , thanks for the info! That helps.
