### ISSUE TITLE
prysm forgets wallet password after update

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum2-docker-compose#218]
Update from `beta-5` to `beta-6` somehow deleted/reset the password for the wallet and the user got error messages like
```
level=error msg="could not open wallet: password did not pass validation: password input cannot be empty" prefix=main
```

After just reimporting the error changes to
```
time="2021-06-05 13:50:13" level=info msg="Enabling web portal to manage the validator client" prefix=node
time="2021-06-05 13:50:13" level=info msg="Opened validator wallet" keymanager-kind=direct prefix=node wallet="/data/wallets/direct"
time="2021-06-05 13:50:13" level=error msg="could not read keymanager for wallet: could not initialize imported keymanager: failed to initialize account store: wrong password for wallet entered: invalid checksum" prefix=main
```

After doing
1) stop the services
2) delete ./data/prysm/validator/wallets
3) reimport again

Validator service resumes operation as expected.

**Comment by stefa2k** [comment]
Possible fix is to adapt update process:
1) copy `./data/prysm/validator/passwords/wallet-password` to `/etc/stereum/prysm-wallet-password.tmp` before updating repos (`git checkout <tag>`)
2) copy `/etc/stereum/prysm-wallet-password.tmp` to `./data/prysm/validator/passwords/wallet-password` after successful update

**Comment by rhythnic** [comment]
A similar thing happened to me.  I am running on mainnet, and after the update to Prysm v1.3.10, the web UI doesn't recognize my account.  The validator is running, I've run the list-accounts command and I can see the account.  The logs indicate that the validator is participating in the epochs successfully, but the web UI isn't seeing the accounts.  In my case, it might not be an issue with this repo, but a bug in Prysm.  I reported it in their Discord.  The above fix didn't work for me.

**Comment by stefa2k** [comment]
Hi @rhythnic thanks for dropping in! As I understand it your validators kept attesting?

**Comment by rhythnic** [comment]
Yes, that's right @stefa2k .  There is a confirmed bug(s) with the web UI in this release, but the validator seems to be working fine.

**Comment by rhythnic** [comment]
Here's the bug:

https://github.com/prysmaticlabs/prysm-web-ui/issues/181
