### ISSUE TITLE
Could not open wallet: no wallet found

### ISSUE THREAD

**Issue by hershkoy** [stereum-dev/ethereum2-docker-compose#22]
I tried to run the prysm-only process, and I got this error on the validator container:

```
time="2020-11-20 10:26:45" level=warning msg="Running on ETH2 Mainnet" prefix=flags
time="2020-11-20 10:26:45" level=error msg="could not open wallet: no wallet found. You can create a new wallet with validator wallet create.If you already did, perhaps you created a wallet in a custom directory, which you can specify using --wallet-dir=/path/to/my/wallet" prefix=main
```

What am I missing?

**Comment by stefa2k** [comment]
Thanks for the inquery, do you try to run on mainnet?

**Comment by hershkoy** [comment]
I think it is my mistake.. I didn't follow instructions in the "Validator accounts with launchpad"

**Comment by wiryonolau** [comment]
> I think it is my mistake.. I didn't follow instructions in the "Validator accounts with launchpad"

Hi can you collaborate.  I created validator_keys using eth2deposit-cli and put it in launchpad/eth2.0-deposit-cli
Then call validator-import-launchpad it response like this

```
WARN flags: Running on ETH2 Mainnet
ERROR main: could not open wallet: no wallet found. You can create a new wallet with validator wallet create.If you already did, perhaps you created a wallet in a custom directory, which you can specify using --wallet-dir=/path/to/my/wallet
```

I try creating the wallet outside docker using "prysm2 validator create wallet" and copy it to that folder, still giving the same error

**Comment by stefa2k** [comment]
@wiryonolau Hi, are you trying to run multiclient or prysm-only?

**Comment by wiryonolau** [comment]
Hi sorry my mistake. I'm using the archived repo  stefa2k/prysm-docker-compose , in their create-account.yaml command it use '**account-v2**' instead of '**account**'.  I thought the one with v2 is newer, when I change it back to '**account**' everything works ok.
