### ISSUE TITLE
Metrics not loading in Grafana

### ISSUE THREAD

**Issue by bmilesp** [stereum-dev/ethereum2-docker-compose#27]
Hello,

I was able to successfully run the docker compose file, adding user 1000 to grifana and it looks like the Overview New dashboard is not loading any metrics:
![image](https://user-images.githubusercontent.com/202549/99968363-0b560400-2d67-11eb-99c3-d78a13b1932d.png)

It looks like the only metrics that seem to be available are the scrape metrics:
![image](https://user-images.githubusercontent.com/202549/99968323-ff6a4200-2d66-11eb-9892-0c9bf26655ab.png)

I wanted to get the dashboard metrics working before I stake anything.

Here are the latest bits of logs for each service:

Geth seems to be sync'd to the head of the chain:
![image](https://user-images.githubusercontent.com/202549/99968021-9da9d800-2d66-11eb-98e2-34f65e09ec47.png)

Beacon_1 seems ok also:
![image](https://user-images.githubusercontent.com/202549/99968148-c29e4b00-2d66-11eb-924b-496a50464b0d.png)

Validator_1 maybe an issue
![image](https://user-images.githubusercontent.com/202549/99967989-91257f80-2d66-11eb-9b32-1b7ed95fb88f.png)

slasher_1 gives me some errors, any idea why?
![image](https://user-images.githubusercontent.com/202549/99967958-866aea80-2d66-11eb-8215-0b04408b8b4f.png)

Grafana_1 successfil login:
![image](https://user-images.githubusercontent.com/202549/99968600-5243f980-2d67-11eb-95a1-1f0c7a47cd0a.png)

All in all, I really like this setup and thank you for all of your work,

-bp

**Comment by stefa2k** [comment]
Hey, thanks for the report! Do you mind letting me know what setup you use? Multiclient, Prysm-only or Lighthouse-only?

**Comment by bmilesp** [comment]
Np! It was the Prysm-only setup.

-bp

**Comment by stefa2k** [comment]
There was an update today that fixed this issue, please apply it:

1. make sure you got the latest version by running `git pull`, if there is an error about local changes run `git stash && git pull && git stash pop`, you might need to resolve conflicts.
2. copy the new `docker-compose.yaml` to your project root `cp compose-examples/prysm-only/docker-compose.yaml .`
3. adapt the `docker-compose.yaml` to your needs, especially grafana's `user: ...`
4. stop and remove the effected containers: `docker-compose stop prometheus grafana && docker-compose rm prometheus grafana`
5. delete the data in `./data/grafana` and `./data/prometheus`
6. start prometheus and grafana again

Please report back if this helped you resolving the issue.

**Comment by hershkoy** [comment]
@stefa2k, I am having similar. I tried your suggestion from about, it didn't work for me. 
I think that the issue, for me, is originating from docker-compose not exposing the service as host name to the network:
```
# curl http://validator:8080/metrics
curl: (6) Could not resolve host: validator; Unknown error
```
curl with the exact ip of the container works. 

![image](https://user-images.githubusercontent.com/13259380/99992453-091f9400-2dbf-11eb-835a-fdc678ed33bf.png)

Any idea what can cause/solve it?

**Comment by hershkoy** [comment]
Thanks to the awesome help of @stefa2k issue was solved. 
My issue was that even though I pulled the update from today, I forgot to copy/update the docker-compose.yaml on the root folder. Specifically these lines:

![image](https://user-images.githubusercontent.com/13259380/100005743-1d20c100-2dd2-11eb-92d6-c15980883521.png)

After update the yaml, I restarted everything and it now works

**Comment by bmilesp** [comment]
@stefa2k Yes the solution you've provided worked! Thanks for an excellent app!

-bp
