### ISSUE TITLE
grafana - prometheus connection incorrectly configured with basic auth

### ISSUE THREAD

**Issue by kumavis** [stereum-dev/ethereum2-docker-compose#30]
the grafana `provisioning-p` configuration sets its prometheus datasource as having basic auth
https://github.com/stereum-dev/ethereum2-docker-compose/blob/87177ea5ca7daddf068aefc40af3b9ca57dc6404/config/grafana/provisioning-p/datasources/datasource.yml#L28-L33
as i understand it [prometheus does not natively support basic auth](https://prometheus.io/docs/guides/basic-auth/#securing-prometheus-api-and-ui-endpoints-using-basic-auth) and it is not otherwise setup by this docker configuration
this misconfiguration prevents grafana from reaching prometheus, resulting in logging like
```
error="Could not find datasource Data source not found" 
```

**Comment by kumavis** [comment]
hmm actually the error may be unrelated... but it works without the auth misconfiguration

**Comment by stefa2k** [comment]
Interesting, I didn't experience any connection issue between grafana and prometheus. However it's correct these settings are unnecessary.
