### ISSUE TITLE
Merge Preparation

### ISSUE THREAD

**Issue by shamoya** [stereum-dev/ethereum2-docker-compose#307]
Hi @stefa2k,

Any plans to update services for the mainnet merge on Sept 6?
I really like this project and I use it in my node, it'll be sad to hear it's no longer active.

Thanks
Ido

**Comment by stefa2k** [comment]
Hey, sorry to say this repo will no longer be maintained. Stereum v1 (this repo is part of it) is EOL as soon as the mainnet forks on the 6th September.

We are working on Stereum v2 to give users a better experience with more flexibility on https://github.com/stereum-dev/ethereum-node which I hope might be interesting for you too.

**Comment by shamoya** [comment]
I'll check it out. Thanks for the update
