### ISSUE TITLE
Add Prysm's web-ui

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum2-docker-compose#4]

**Comment by stefa2k** [comment]
```
  --grpc-gateway-corsdomain value      Comma separated list of domains from which to accept cross origin requests (browser enforced). This flag has no effect if not used with --grpc-gateway-port. (default: "http://localhost:4242,http://127.0.0.1:4242,http://localhost:4200")
  --grpc-gateway-host value            The host on which the gateway server runs on (default: "127.0.0.1")
  --grpc-gateway-port value            Enable gRPC gateway for JSON requests (default: 7500)
```

**Comment by gbayasgalan** [comment]
No response, perhaps beacon node or validator client are not running -
`Access to XMLHttpRequest at 'http://127.0.0.1:3500/eth/v1alpha1/beacon/chainhead' from origin 'http://localhost:7500' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
