### ISSUE TITLE
Lighthouse: include additional monitoring

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum2-docker-compose#75]
https://lighthouse-book.sigmaprime.io/validator-monitoring.html

https://github.com/sigp/lighthouse-metrics/blob/master/dashboards/ValidatorMonitor.json

**Comment by stefa2k** [comment]
blocked by #78

**Comment by stefa2k** [comment]
@gbayasgalan this is resolved, correct?

**Comment by gbayasgalan** [comment]
Yes. The validator monitoring for lighthouse working

**Comment by gbayasgalan** [comment]
I mean it‘s done, working fine, ready to use
